# Welcome to the config.yml!
# Please contact me if this plugin isn't working as intended!

modules:
  unicode-grabber:
    message: "&b[UC] &f%unicode%" # & for chat colors %unicode% for the unicode character!